Django/django/restapp/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

Django/django/restapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), # /blog/
    # # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'), # /blog/detail/1
    # # 글 작성
    path("write/", views.Write.as_view(), name='write'), # /blog/write/
    # # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # # 코멘트 작성
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # # 코멘트 삭제
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    # # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

Django/django/restapp/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content
    # admin 페이지에 가면 comment on '포스트제목'의 댓글들을 확인할 수 있다.
    # id 값 대신 제목을 표시할 수 있다.     
    
    
class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    def __str__(self):
        return self.name 

Django/django/restapp/blog/forms.py
# blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

# Form : html에 있는 form태그
# forms.Form 일반폼 
# Model Form : 모델(Model)과 연결된 폼으로 폼을 저장하면 연결된 모델의 데이터를 저장할 수 있는 폼
# forms.ModelForm
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post # 사용할 모델
        # PostForm에서 사용 할 Post 모델의 속성
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'cols':'35'}),
        }
        
        labels = {
            'title' : '제목',
            'content' : '내용',
        }
# 즉, PostForm은 Post모델과 연결된 폼이고 Post모델의 title과 content를 사용 한다고 정의

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        # 이 fields만 받을거야 ! 
        widgets = {
            'content' : forms.Textarea(attrs={'rows': '5', 'cols':'35'})
        }
        # widgets는 content를 보여주겠다! 라는 함수
        # attrs는 태그 속성이다 html에 있는 태그만 바꿀 수 있다.
        

class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = ['name']
        # 사용자에게 값을 가져와야함
    

Django/django/restapp/blog/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.throttling import UserRateThrottle ## Throttle
from .models import Post, Comment, HashTag
from .forms import PostForm
from .serializers import PostSerializer, CommentSerializer, HashTagSerializer

## Post
class Index(APIView):
    ## Throttle
    throttle_classes = [UserRateThrottle]
    
    def get(self, request):
        posts = Post.objects.all()
        serialized_posts = PostSerializer(posts, many=True) # 직렬화
        # ORM(장고의SQL)은 파이썬 객체이기 때문에 클라이언트에게 보내줄 땐 문자열로 변환해서 보내줘야 하기 때문에 직렬화를 통해서 보내줘야함
        return Response(serialized_posts.data)
        # 직렬화 된 상태로 데이터만 넘어간다
        

class Write(APIView):
    ## Throttle
    throttle_classes = [UserRateThrottle]
    # Write 관련된 API는 POST로 날려버리면 돼서 따로 클라이언트에게 보여주는 template가 필요없음
    # def get(self, request):
    #     # 사용자 작성 Form만들어서 보내줌
    #     pass
    def post(self, request):
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid():
            # 유저 저장하기 전에 commit=False로 저장 미룸
            post = serializer.save(writer=request.user)
            post.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Update(APIView):
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        serializer = PostSerializer(post) # 보내는 직렬화?
        return Response(serializer.data)
        # 직렬화 된 포스트를 돌려주는구나
        # 여기선 get을 하는 이유? 전의 수정하기 전 값을 되돌려줘야함 위의 글 작성에선 get을 쓰지 않는 이유는 화면 form만 보여줘야하니까 데이터를 굳이 보내주지 않아도됨
    
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        serializer = PostSerializer(post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Delete(APIView):
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        # serializer = PostSerializer(post)
        # if serializer.is_valid():
        post.delete()
        return Response({'msg': 'Post deleted'}, status=status.HTTP_204_NO_CONTENT)


class DetailView(APIView):
    def get(self, request, pk):
        post = Post.objects.prefetch_related('comment_set', 'hashtag_set').get(pk=pk)

        comments = post.comment_set.all()
        serialized_comments = CommentSerializer(comments, many=True).data
        
        hashtags = post.hashtag_set.all()
        serialized_hashtags = HashTagSerializer(hashtags, many=True).data
        

        comment_form = CommentForm()
        hashtag_form = HashTagForm()

        data = {
            "title": "Blog",
            "post_id": pk,
            "comments": serialized_comments,
            "hashtags": serialized_hashtags,
            "comment_form": comment_form,
            "hashtag_form": hashtag_form,
        }
        
        return Response(data)


## Comment
class CommentWrite(APIView):
    def post(self,request, pk):
        serializer = CommentSerializer(data=request.data)
        if serializer.is_valid():
            comment = serializer.save(writer=request.user)
            comment.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

class CommentDelete(APIView):
    def post(self,request,pk):
        comment = Comment.objects.get(pk=pk)
        comment.delete()
        serializer = CommentSerializer(comment)
        return Response(serializer.data, status=status.HTTP_204_NO_CONTENT)


### HashTag
class HashTagWrite(APIView):
    def post(self,request, pk):
        serializer = HashTagSerializer(data=request.data)
        if serializer.is_valid():
            hashtag = serializer.save(writer=request.user)
            hashtag.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class HashTagDelete(APIView):
    def post(self,request,pk):
        hashtag = HashTag.objects.get(pk=pk)
        hashtag.delete()
        serializer = HashTagSerializer(hashtag)
        return Response(serializer.data, status=status.HTTP_204_NO_CONTENT)
        
        

Django/django/restapp/blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
    {{ form }}
</div>

Django/django/restapp/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <h2>제목: {{ post_title }}</h2>

    {% if post_writer == request.user %}
    <a href="{% url 'blog:edit' pk=post_id %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' pk=post_id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn">
    </form>
    {% endif %}

    <p>내용: {{ post_content }}</p>
    <p>작성자: {{ post_writer }}</p>
    <p>작성일: {{ post_created_at }}</p>
    <hr>

    <!-- 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            {% with form=comment_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ comment_form.content }}
        {% endif %}
        <input type="submit" value="댓글 작성">
    </form>
    <br>
    <!-- comments -->
    <!-- if 문 -->
    {% if comments %}
        <!-- for 문 -->
        <ul>
            {% for comment in comments %}
            <!-- 내용, 작성시간, 삭제 버튼 -->
                <li>{{ comment.content }} / {{ comment.created_at }}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class='btn'>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>댓글이 없습니다.</p>
    {% endif %}
    <hr>
    <!-- 태그작성 화면 -->
    <h3>해시태그</h3>
    <form action="{% url 'blog:tag-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if hashtag_form.errors %}
            {% with form=hashtag_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ hashtag_form.name }}
        {% endif %}
        <input type="submit" value="태그 작성">
    </form>
    {% if hashtags %}
    <ul>
        {% for hashtag in hashtags %}
        <li>
            {{ hashtag }}
            {% if hashtag.writer == request.user %}
                <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="X" class='btn'>
                </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <br>
    <p>해시태그가 없습니다.</p>
    {% endif %}


{% endblock %}

Django/django/restapp/blog/templates/blog/post_edit.html
{% extends 'base.html' %}

<!-- 사용자가 수정을 해야하기 때문에 form을 열어준다 -->
<!-- 수정 form -->
{% block content %}

{% if form.errors %}
    {% include 'blog/form_error.html' %}
{% else %}
    <form action="{% url 'blog:edit' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정" class="btn btn-outline-success">
    </form>
    {% endif %}
    {% endblock %}


    <!-- title -->
    <!-- {{ form.title.label_tag }} 1  -->
    <!-- <input type="text" name="{{ form.title.name }}" value="{{ form.initial.title }}"> 1-->
    <!-- form.initial.title은 initial['title']=post.title에서 pk로 현재 객체를 가져온 것  -->

    <!-- name을 지정해주는 이유 !  -->
    <!-- model로 form을 정해주지 않았고 template_name으로 html 템플릿(화면)만 연결해두었기 때문에 html 안에 있는 form이 제대로 동작하려면 해당 form 안에 name값이 제대로 정해져 있어야 post 요청이 성공적으로 수행됩니다~! 
    왜냐하면 서버에서 form 태그 자체에서 input을 감지하는 목적으로 사용하는 속성이 name 이기 때문에 그 부분이 제대로 충족되어야 html 안에서 form 요청이 제대로 수행될 수 있습니다  -->

    <!-- content -->

    <!-- {{ form.content.label_tag }}
    <textarea type="text" name="{{ form.content.name }}">{{ form.initial.content }}</textarea>
    <br> 1-->

Django/django/restapp/blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
    <p>블로그 글 작성 화면</p>
    <!-- 제목 -->
    <!-- 내용 -->
    <!-- form action이 실행이 되는 것은 view의 writer경로를 타게됨 // form(submit버튼)이 실행되면 url blog:write로 요청을 하게 됨--> 
    <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        <!-- views.py Write 클래스에 보내준 form을 이용 -->
        <!-- p형태로 form을 불러오겠다 -->
        {{ form.as_p }}
        <!-- PostForm의 객체 폼의 정의한 title, content속성에 해당하는 html코드를 자동으로 생성 -->
        <input type="submit" value="작성" class="btn btn-outline-success">
    </form>
{% endblock %}

Django/django/restapp/blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <p>블로그 게시판 첫 화면입니다.</p>
    <form action="{% url 'blog:write' %}" method="get">
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.GET.next }}">
        <input type="submit" value="글 작성" class="btn btn-outline-success">
    </form>

    <!-- '글작성 화면' 경로 a태그 넣어주기 -->
    <!-- get으로 보여주기 때문에 get form이 열릴 것이다. -->
    <!-- <a href="{% url 'blog:write' %}" class="btn btn-outline-success">글 작성</a> 1-->

    <!-- 조건문 -->
    <!-- 글이 있을 때 : 테이블 출력-->
    {% if posts %}
    <!-- posts views.py에서 context_object_name 선언 -->
        <table class="table-bordered">
            <thead class="table-light">
                <tr>
                    <td>제목</td>
                    <td>내용</td>
                    <td>작성자</td>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <!-- posts 안에 post 순회 -->
                <!-- 예를들어 pk=post.pk -> 순회를 도는 post를 써줌 -->
                <tr>
                    <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a></td>
                    <td>{{ post.content }}</td>
                    <td>{{ post.writer }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <!-- 글이 없을 때 문구출력 -->
    <p>작성된 게시물이 없습니다.</p>
    <!-- if문을 닫아줌 -->
    {% endif %}


{% endblock %}