Django/django_blog_tutorial/mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.postlist, name='postlist'),
    path('<int:pk>/', views.postdetail, name='postdetail'),
    path('write/', views.write, name='postwrite'),
    path('edit/<int:pk>', views.edit, name='postedit'),
    path('delete/<int:pk>', views.delete, name='postdelete'),
    path('<int:pk>/new_comment/', views.new_comment, name='new_comment'),
    path('update_comment/<int:pk>/', views.update_comment, name='update_comment'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('category/<str:slug>/', views.category_page, name='category_page'),
    path('tag/<str:slug>/', views.tag_page, name='tag_page'),
]

Django/django_blog_tutorial/mysite/tutorialblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/django_blog_tutorial/mysite/blog/models.py
from django.db import models
# from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    head_image = models.ImageField(
        upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(
        upload_to='blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)

    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return self.file_upload.name.split('/')[-1]

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=200, db_index=True,
                            unique=True, allow_unicode=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'


class Tag(models.Model):
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=200, db_index=True,
                            unique=True, allow_unicode=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'[{self.post}] {self.content} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.post.pk}/#comment-{self.pk}'

    class Meta:
        ordering = ['-id']

Django/django_blog_tutorial/mysite/blog/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Category, Tag, Comment
from .forms import CommentForm
from django.utils.text import slugify
from django.db.models import Q


class PostList(ListView):
    model = Post
    ordering = '-pk'
    # template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all().order_by('-name')
        context['no_category_post_count'] = Post.objects.filter(
            category=None).count()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        search_keyword = self.request.GET.get('q')

        if search_keyword:
            # queryset = queryset.filter(title__icontains=search_keyword)
            # distinct()는 중복을 제거합니다.
            # Q는 |(or), &(and), ~(not) 연산자를 사용할 수 있습니다.
            # icontains는 대소문자를 구분하지 않는 검색입니다.
            queryset = queryset.filter(
                Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(tags__name__icontains=search_keyword)).distinct()

        return queryset


class PostDetail(DetailView):
    model = Post
    # template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('-name')
        context['no_category_post_count'] = Post.objects.filter(
            category=None).count()
        context['comment_form'] = CommentForm
        return context


def category_page(request, slug):
    category = Category.objects.get(slug=slug)
    categories = Category.objects.all().order_by('-name')
    context = {
        'post_list': Post.objects.filter(category=category).order_by('-pk'),
        'categories': categories,
        'no_category_post_count': Post.objects.filter(category=None).count(),
        'category': category,
        'category_list': Category.objects.all().order_by('-name'),
    }
    return render(request, 'blog/post_list.html', context)


def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    print(tag)
    post_list = tag.post_set.all()
    categories = Category.objects.all().order_by('-name')
    context = {
        'post_list': post_list,
        'categories': categories,
        'no_category_post_count': Post.objects.filter(category=None).count(),
        'tag': tag,
        'category_list': Category.objects.all().order_by('-name'),
    }
    return render(request, 'blog/post_list.html', context)


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'head_image',
            'file_upload', 'category']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            # 원래 기존에 리턴하던 값을 response에 담아둡니다.
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    # self.object는 새로만든 Post 객체
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image',
            'file_upload', 'category', 'tags']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(PostUpdate, self).form_valid(form)
        else:
            return redirect('/blog/')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            post = self.get_object()
            if post.author == request.user:
                return super().dispatch(request, *args, **kwargs)
            else:
                return HttpResponse('You are not allowed to update this post')
        return super().dispatch(request, *args, **kwargs)


def new_comment(request, pk):
    if request.user.is_authenticated:
        post = Post.objects.get(pk=pk)
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                # commit=False를 하면, DB에 바로 저장되지 않습니다.
                # 대신, 메모리에 Comment 객체를 하나 생성해 줍니다.
                comment = form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            form = CommentForm()
        return render(request, 'blog/comment_form.html', {'form': form})


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(CommentUpdate, self).form_valid(form)
        else:
            return redirect('/blog/')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            comment = self.get_object()
            if comment.author == request.user:
                return super().dispatch(request, *args, **kwargs)
            else:
                return HttpResponse('You are not allowed to update this comment')
        return super().dispatch(request, *args, **kwargs)


def delete_comment(request, pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=pk)
        if comment.author == request.user:
            comment.delete()
            return redirect(comment.post.get_absolute_url())
        else:
            return HttpResponse('You are not allowed to delete this comment')
    return redirect('/blog/')


postlist = PostList.as_view()
postdetail = PostDetail.as_view()
write = PostCreate.as_view()
edit = PostUpdate.as_view()
delete = DeleteView.as_view()
update_comment = CommentUpdate.as_view()

Django/django_blog_tutorial/mysite/blog/templates/blog/bloglist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bloglist</title>
</head>
<body>
    {% for i in posts %}
        <p>{{ i.title }}</p>
        <p>{{ i.content }}</p>
        <p>{{ i.created_at }}</p>
    {% endfor %}
</body>
</html>

Django/django_blog_tutorial/mysite/blog/templates/blog/comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commentform</title>
</head>
<body>
    <h1>edit comment</h1>
    <form method="post">
        {% csrf_token %}
        <table class="table">
            {{form}}
        </table>
        <button type="submit">작성</button>
    </form>
</body>
</html>

Django/django_blog_tutorial/mysite/blog/templates/blog/post_detail.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postdetail</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <!-- fontawesome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <h1>detail</h1>
    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">About</a></li>
        </ul>
    </nav>
    <main id="main">
    <p>{{ post.title }}</p>
    <p>{{ post.content }}</p>
    {% if post.head_image %}
    <img src="{{ post.head_image.url }}" alt="" srcset="">
    {% endif %}
    {% if post.file_upload %}
    <a href="{{ post.head_image.url }}" alt="" srcset="">
    Download:
        {% if post.get_file_ext == 'csv' %}
            <i class="fas fa-file-csv"></i>
        {% elif post.get_file_ext == 'pdf' %}
            <i class="fas fa-file-pdf"></i>
        {% elif post.get_file_ext == 'zip' %}
            <i class="fas fa-file-archive"></i>
        {% elif post.get_file_ext == 'jpg' %}
            <i class="fas fa-file-image"></i>
        {% elif post.get_file_ext == 'png' %}
            <i class="fas fa-file-image"></i>
        {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
            <i class="fas fa-file-word"></i>
        {% elif post.get_file_ext == 'pptx' or post.get_file_ext == 'ppt' %}
            <i class="fas fa-file-powerpoint"></i>
        {% elif post.get_file_ext == 'xls' %}
            <i class="fas fa-file-excel"></i>
        {% elif post.get_file_ext == 'mp3' %}
            <i class="fas fa-file-audio"></i>
        {% elif post.get_file_ext == 'mp4' %}
            <i class="fas fa-file-video"></i>
        {% else %}
            <i class="fas fa-file"></i>
        {% endif %}
        {{ post.file_upload.name }}
    {% endif %}
    <p>{{ post.created_at }}</p>
    <p>by {{ post.author }}</p>
    {% if post.comment_set.exists %}
        <h2>댓글</h2>
        {% for comment in post.comment_set.all %}
            <p>{{ comment.content }}</p>
            <p>{{ comment.created_at }}</p>
            <p>by {{ comment.author }}</p>
            {% if user.is_authenticated and comment.author == user %}
            <a role="button" href="/blog/update_comment/{{comment.pk}}">edit</a>
            <a role="button" href="/blog/delete_comment/{{comment.pk}}">delete</a>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>아직 댓글이 없습니다.</p>
    {% endif %}
    {% if user.is_authenticated %}
    <p>로그인 되었습니다.</p>
    <form id="comment-form" action="{{post.get_absolute_url}}new_comment/" method="post">
        {% csrf_token %}
        {{comment_form.as_p}}
        <button type="submit">작성</button>
    </form>
    {% else %}
    <p>로그인이 필요합니다.</p>
    {% endif %}
    </main>

</body>
</html>

Django/django_blog_tutorial/mysite/blog/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postform</title>
    <!-- Toast Editor 2.0.0과 의존성 -->
    <link
        rel="stylesheet"
        href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"
    />
    <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
            {{form}}
            <tr>
                <th><label for="id_tags">Tags:</label></th>
                <td><input type="text" name="tags_str" id="id_tags_str"></td>
            </tr>
            <tr>
                <th><label for="id_content_editor">Content_editor:</label></th>
                <td><div id="editor"></div></td>
            </tr>
        </table>
        <button type="submit" id="submitbtn">제출</button>
    </form>
    <script>
        const Editor = toastui.Editor;

        const editor = new Editor({
            el: document.querySelector("#editor"),
            height: "600px",
            initialEditType: "markdown",
            previewStyle: "vertical",
        });

        // editor.getHTML()
        // editor.getMarkdown()
        document.getElementById('submitbtn').addEventListener('click', function(){
            const markdownContent = editor.getMarkdown();
            document.getElementById('id_content').value = markdownContent;
        });
    </script>
</body>
</html>

Django/django_blog_tutorial/mysite/blog/templates/blog/post_list.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <h1>blog</h1>
    <input type="text" name="q" id="search-input">
    <button id="search-btn">검색</button>
    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">About</a></li>
        </ul>
    </nav>
    <main id="main">
        {% if post_list.exists %}
        {% for post in post_list %}
            <h2>{{ post.title }}</h2>
            <p>{{ post.content | truncatewords:45 }}</p>
            <p>{{ post.created_at }}</p>
            <p>by {{ post.author }}</p>
        {% endfor %}
        {% else %}
            <p>아직 게시물이 없습니다.</p>
        {% endif %}
    </main>
    <aside>
        <h2>카테고리</h2>
        <ul>
            <!-- post_set은 필드명_set 으로 이해하셔야 합니다. 그래서 구글에서 post_set으로 검색해도 아무것도 안나올거에요. category에 post라는 필드가 있고, 그 해당 category 레코드에 연결된 post 레코드들이 여럿있겠죠. post_set은 그 post 레코드들을 의미합니다.  -->
            {% for category in category_list %}
            <li><a href="{{ category.get_absolute_url }}">{{ category.name }} {{ category.post_set.count }}</a></li>
            {% endfor %}
        </ul>
    </aside>
    <script>
        document.querySelector('#search-btn').addEventListener('click', () => {
            const searchInput = document.querySelector('#search-input');
            const searchValue = searchInput.value;
            location.href = `/blog/?q=${searchValue}`;
        });
    </script>
</body>
</html>